### ISSUE TITLE
options.templateSettings doesn't work

### ISSUE THREAD

**Issue by shlangus** [ingro/gulp-template-compile#11]
When I try to pass any templateSettings by define options.templateSettings, for example like here:

```
templateCompile({
    'namespace': 'myNamespace',
    'templateSettings': {
        variable: 'data'
    }
});
```
there is no effect.
I think that the problem is second argument [at line 38](https://github.com/ingro/gulp-template-compile/blob/master/index.js#L38), which must be options.templateSettings instead of false.

**Comment by ingro** [comment]
Thanks for reporting, this should be fixed by #12 !
